version: '3'

services:
  postgres-dev:
    container_name: postgres-spring-kotlin-exchange
    image: postgres:14-alpine
    ports:
      - "5440:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 30s
      retries: 5

  postgres-test:
    container_name: postgres-spring-kotlin-exchange-test
    image: postgres:14-alpine
    ports:
      - "5441:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange-test
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 30s
      retries: 5